export const streetSafetyScenarios = Object.freeze([
  {
    id: 'steady-red',
    category: 'Signal lights',
    title: 'Steady red light',
    prompt: 'The signal facing your lane is solid red. What is the safest first action?',
    options: ['Stop at the proper line and wait for a permitted, safe movement.', 'Speed up before cross traffic starts.', 'Roll through if the road looks quiet.'],
    answer: 0,
    why: 'A steady red signal requires a stop. Any movement after stopping must be both permitted and safe under local rules.',
    hint: 'Red controls your lane even when the intersection looks empty.',
    visual: 'signal-red'
  },
  {
    id: 'steady-yellow',
    category: 'Signal lights',
    title: 'Steady yellow light',
    prompt: 'A green signal changes to solid yellow as you approach. What does yellow tell you?',
    options: ['Race the red light.', 'The signal is changing; stop if you can do so safely.', 'Stop instantly even if hard braking would be unsafe.'],
    answer: 1,
    why: 'A steady yellow light warns that red is coming. Stop when you can do so safely; it is not a signal to speed up.',
    hint: 'Yellow means the protected time is ending.',
    visual: 'signal-yellow'
  },
  {
    id: 'steady-green',
    category: 'Signal lights',
    title: 'Steady green light',
    prompt: 'The signal turns green, but a person is still finishing the crosswalk. What should happen?',
    options: ['Honk so the person moves faster.', 'Enter the crosswalk because green always means go immediately.', 'Wait until the intersection and crosswalk are clear, then proceed safely.'],
    answer: 2,
    why: 'Green permits movement only when the way is clear. People and vehicles already in the intersection still need room to finish safely.',
    hint: 'Green gives permission, not a guarantee that the path is clear.',
    visual: 'signal-green'
  },
  {
    id: 'flashing-red',
    category: 'Signal lights',
    title: 'Flashing red light',
    prompt: 'A traffic signal is flashing red. How should it be treated?',
    options: ['Like a flashing yellow warning.', 'Stop fully, then continue only when it is safe and your turn.', 'Ignore it after dark.'],
    answer: 1,
    why: 'A flashing red signal is treated like a STOP control: stop first, check carefully, and proceed only when safe.',
    hint: 'Flashing red still means stop.',
    visual: 'signal-flashing-red'
  },
  {
    id: 'flashing-yellow',
    category: 'Signal lights',
    title: 'Flashing yellow light',
    prompt: 'The signal is flashing yellow at an intersection. What is the safe response?',
    options: ['Slow down, stay alert, and proceed with caution.', 'Stop and wait for a green light that may never appear.', 'Speed through before it changes.'],
    answer: 0,
    why: 'A flashing yellow signal warns you to slow down and proceed cautiously. Watch for crossing traffic and people.',
    hint: 'Flashing yellow is a caution signal, not a race signal.',
    visual: 'signal-flashing-yellow'
  },
  {
    id: 'red-arrow',
    category: 'Signal lights',
    title: 'Red arrow',
    prompt: 'A red arrow points left. What does it control?',
    options: ['Only pedestrians.', 'Traffic going straight.', 'Movement in the arrow’s direction must stop until a signal permits it.'],
    answer: 2,
    why: 'A red arrow stops movement in the direction shown. Wait for an allowed signal and a clear path.',
    hint: 'Match the arrow direction to the movement it controls.',
    visual: 'arrow-red'
  },
  {
    id: 'green-arrow',
    category: 'Signal lights',
    title: 'Green arrow',
    prompt: 'A green arrow points left. What should a road user remember?',
    options: ['The turn is required even if the crosswalk is occupied.', 'The turn is permitted, but the path still must be clear.', 'Oncoming traffic always has a green light too.'],
    answer: 1,
    why: 'A green arrow permits movement in its direction, but road users must still avoid people or vehicles remaining in the path.',
    hint: 'Permission to turn never removes the need to look.',
    visual: 'arrow-green'
  },
  {
    id: 'walk-signal',
    category: 'Signal lights',
    title: 'WALK signal',
    prompt: 'The white walking-person symbol appears. What should a pedestrian do?',
    options: ['Check for turning vehicles, then begin crossing when clear.', 'Run without looking because every vehicle must already be gone.', 'Wait in the middle of the roadway.'],
    answer: 0,
    why: 'The WALK symbol allows a pedestrian to begin crossing, but staying alert for turning or unexpected vehicles is still important.',
    hint: 'A signal helps, and looking helps too.',
    visual: 'pedestrian-walk'
  },
  {
    id: 'flashing-dont-walk',
    category: 'Signal lights',
    title: 'Flashing hand signal',
    prompt: 'The orange hand begins flashing before you step off the curb. What is the safe choice?',
    options: ['Start crossing slowly.', 'Stand in the street and wait for the countdown.', 'Do not begin crossing; wait for the next WALK signal.'],
    answer: 2,
    why: 'A flashing orange hand means do not start crossing. A person already in the crosswalk should continue toward safety without delaying.',
    hint: 'Ask whether you have already started crossing.',
    visual: 'pedestrian-wait'
  },
  {
    id: 'railroad-flashers',
    category: 'Signal lights',
    title: 'Railroad red flashers',
    prompt: 'Red railroad lights are flashing and the gate is lowering. What must road users do?',
    options: ['Go around the gate if no train is visible.', 'Stop and wait until the warning system ends and the crossing is safe.', 'Stop on the tracks for a better view.'],
    answer: 1,
    why: 'Flashing railroad lights and a lowering gate warn that rail traffic is approaching or present. Never go around a lowered gate or stop on tracks.',
    hint: 'Trains cannot stop quickly, and the gate is never a shortcut.',
    visual: 'railroad'
  },
  {
    id: 'school-crossing',
    category: 'Caution signs',
    title: 'School crossing',
    prompt: 'A fluorescent yellow-green school crossing sign is ahead. What should you expect?',
    options: ['A freeway entrance.', 'Only school buses may continue.', 'Children may be nearby; slow down and watch for crossing controls.'],
    answer: 2,
    why: 'School-area signs warn that children and school activity may be nearby. Slow attention and posted controls matter.',
    hint: 'The five-sided school shape and walking figures are clues.',
    visual: 'sign-school'
  },
  {
    id: 'road-work',
    category: 'Caution signs',
    title: 'Road work ahead',
    prompt: 'An orange diamond says ROAD WORK AHEAD. What does orange usually mean here?',
    options: ['Temporary construction or maintenance conditions are ahead.', 'A permanent hospital entrance.', 'The roadway has no rules.'],
    answer: 0,
    why: 'Orange signs mark temporary work-zone conditions. Expect workers, equipment, changed lanes, and directions that may differ from normal.',
    hint: 'Orange is the work-zone color.',
    visual: 'sign-road-work'
  },
  {
    id: 'slippery-wet',
    category: 'Caution signs',
    title: 'Slippery when wet',
    prompt: 'A yellow diamond shows a car with wavy skid marks. What is it warning about?',
    options: ['A car wash entrance.', 'Wet pavement may reduce traction, so use smoother movements and a safer speed.', 'Drivers should weave between lanes.'],
    answer: 1,
    why: 'Water can reduce tire grip. Slower speed, more space, and smooth steering or braking help reduce sudden loss of control.',
    hint: 'The wavy lines show the tires may lose grip.',
    visual: 'sign-slippery'
  },
  {
    id: 'merge-warning',
    category: 'Caution signs',
    title: 'Merge warning',
    prompt: 'A yellow sign shows one traffic line joining another. What should road users prepare for?',
    options: ['The road ends immediately.', 'Everyone must stop in both lanes.', 'Traffic streams will join, so look, signal, and create safe space.'],
    answer: 2,
    why: 'A merge warning gives road users time to notice joining traffic and cooperate instead of making a sudden move.',
    hint: 'Two paths are becoming one shared flow.',
    visual: 'sign-merge'
  },
  {
    id: 'flagger-ahead',
    category: 'Caution signs',
    title: 'Flagger ahead',
    prompt: 'A work-zone sign shows a person holding a flag. What should a driver expect?',
    options: ['A trained worker may direct traffic; slow down and follow the signal.', 'Traffic laws are paused inside the work zone.', 'Only construction trucks need to pay attention.'],
    answer: 0,
    why: 'Flaggers guide traffic through temporary work areas. Slow down early and follow their STOP or SLOW direction.',
    hint: 'A person’s temporary direction can control the work-zone lane.',
    visual: 'sign-flagger'
  },
  {
    id: 'pedestrian-crossing',
    category: 'Caution signs',
    title: 'Pedestrian crossing',
    prompt: 'A warning sign shows a person walking near a marked crossing. What should road users do?',
    options: ['Assume people will always wait.', 'Watch for people and be ready to yield or stop as required.', 'Use the crosswalk as a parking space.'],
    answer: 1,
    why: 'Pedestrian warnings mark places where people may cross. Slowing attention helps everyone see and respond in time.',
    hint: 'Look beyond the sign for people near both curbs.',
    visual: 'sign-pedestrian'
  },
  {
    id: 'bicycle-crossing',
    category: 'Caution signs',
    title: 'Bicycle crossing',
    prompt: 'A yellow warning sign shows a bicycle. What is the useful clue?',
    options: ['Bicycles are banned from every road ahead.', 'A bicycle shop is having a sale.', 'People on bikes may enter or cross the roadway; look carefully and share space.'],
    answer: 2,
    why: 'The bicycle symbol warns that riders may be present or crossing. Check mirrors and blind areas before moving across their path.',
    hint: 'The symbol warns about who may be nearby.',
    visual: 'sign-bicycle'
  },
  {
    id: 'flooded-road',
    category: 'Caution signs',
    title: 'Water over roadway',
    prompt: 'A barricade and warning sign mark water covering the road. What is the safest choice?',
    options: ['Do not enter the water; turn around and use a safe route.', 'Follow the vehicle ahead because it knows the depth.', 'Drive faster so the tires stay on top.'],
    answer: 0,
    why: 'Water can hide road damage and may be deeper or faster than it looks. Never use another vehicle as proof that a flooded crossing is safe.',
    hint: 'If you cannot see the road surface, you cannot judge the crossing.',
    visual: 'scene-flood'
  },
  {
    id: 'emergency-vehicle-approaching',
    category: 'Emergency awareness',
    title: 'Siren approaching',
    prompt: 'An ambulance approaches from behind using lights and a siren. What is the safe response?',
    options: ['Race it to the next intersection.', 'Stay calm, yield, and make a clear path as local law directs.', 'Stop immediately in the middle of an intersection.'],
    answer: 1,
    why: 'Emergency vehicles need a predictable clear path. Signal, move and stop only where it is safe and legal, and follow local rules.',
    hint: 'Be predictable and make room without creating a second emergency.',
    visual: 'emergency-approaching'
  },
  {
    id: 'move-over',
    category: 'Emergency awareness',
    title: 'Flashing lights on the shoulder',
    prompt: 'A stationary emergency vehicle has flashing lights beside the road. What should approaching drivers do?',
    options: ['Move over when safe, or slow down when a safe lane change is not possible.', 'Maintain speed and pass as close as possible.', 'Stop beside the responders to watch.'],
    answer: 0,
    why: 'Move-over laws protect responders and stopped road users. Create a lane of space when safe, or slow down when you cannot safely change lanes.',
    hint: 'Give the people beside the road more space.',
    visual: 'emergency-shoulder'
  },
  {
    id: 'school-bus-yellow',
    category: 'Emergency awareness',
    title: 'School bus yellow flashers',
    prompt: 'A school bus ahead begins flashing yellow lights. What do they warn?',
    options: ['The bus is speeding up.', 'Children may pass only behind the bus.', 'The bus is preparing to stop; slow down and prepare to stop.'],
    answer: 2,
    why: 'Flashing yellow school-bus lights give advance warning that the bus is preparing to stop to load or unload children.',
    hint: 'Yellow warns about the stop that is coming next.',
    visual: 'bus-yellow'
  },
  {
    id: 'school-bus-red',
    category: 'Emergency awareness',
    title: 'School bus red flashers',
    prompt: 'A stopped school bus displays flashing red lights and an extended stop arm. What is the safe meaning?',
    options: ['Pass slowly if no child is visible.', 'Stop and wait as required; children may be crossing.', 'Honk before passing the stop arm.'],
    answer: 1,
    why: 'Flashing red bus lights and the stop arm protect children boarding or leaving. Stop and wait as required; divided-road rules can vary by location.',
    hint: 'Red lights and the STOP arm are active controls.',
    visual: 'bus-red'
  },
  {
    id: 'fire-lane',
    category: 'Emergency awareness',
    title: 'Fire lane — no parking',
    prompt: 'A curbside sign says FIRE LANE — NO PARKING. Why must the space stay clear?',
    options: ['Emergency crews may need immediate access.', 'It is reserved for delivery trucks.', 'It becomes regular parking after dark.'],
    answer: 0,
    why: 'Fire lanes provide access for emergency vehicles and equipment. A vehicle left there can delay help.',
    hint: 'Think about the large vehicles and hoses that may need the space.',
    visual: 'sign-fire-lane'
  },
  {
    id: 'evacuation-route',
    category: 'Emergency awareness',
    title: 'Evacuation route',
    prompt: 'A white square sign contains a blue circle, arrow, and EVACUATION ROUTE words. What does it mark?',
    options: ['A daily shortcut that ignores other signs.', 'A place to park during an emergency.', 'A planned direction to follow when officials order an evacuation.'],
    answer: 2,
    why: 'Evacuation-route signs mark planned emergency travel directions. Follow official instructions and all temporary traffic controls during a real evacuation.',
    hint: 'The route matters when emergency officials activate a plan.',
    visual: 'sign-evacuation'
  },
  {
    id: 'vehicle-hazards',
    category: 'Vehicle & road hazards',
    title: 'Vehicle hazard flashers',
    prompt: 'Both amber turn lights on a stopped car blink together. What should you understand?',
    options: ['The car is definitely turning both directions.', 'The vehicle may be stopped, disabled, or warning of a hazard; slow and give space.', 'The driver is asking you to pass immediately.'],
    answer: 1,
    why: 'Hazard flashers warn that a vehicle or situation needs extra attention. Do not assume they give permission to pass.',
    hint: 'Both sides blinking together signal a warning, not a turn.',
    visual: 'vehicle-hazards'
  },
  {
    id: 'brake-lights',
    category: 'Vehicle & road hazards',
    title: 'Brake lights',
    prompt: 'The red lights on the back of the vehicle ahead glow brighter. What is the clue?',
    options: ['The vehicle is reversing.', 'The driver wants you to follow closer.', 'The vehicle is slowing or stopping; ease off and keep safe space.'],
    answer: 2,
    why: 'Bright red brake lights signal slowing or stopping. More following space gives you time to respond smoothly.',
    hint: 'Red rear lights that brighten are about speed changing.',
    visual: 'vehicle-brake'
  },
  {
    id: 'reverse-lights',
    category: 'Vehicle & road hazards',
    title: 'White reverse lights',
    prompt: 'White lights come on at the rear of a parked vehicle. What should a nearby pedestrian or rider expect?',
    options: ['The vehicle may back up; stay visible and out of its path.', 'The vehicle is parked forever.', 'The driver has seen every blind spot.'],
    answer: 0,
    why: 'White reverse lights show that reverse gear is engaged. The driver may not see every nearby person or object, so stay clear.',
    hint: 'White rear lights are different from red brake lights.',
    visual: 'vehicle-reverse'
  },
  {
    id: 'turn-signal',
    category: 'Vehicle & road hazards',
    title: 'Turn signal blinking',
    prompt: 'The vehicle ahead has one amber signal blinking. What is the careful interpretation?',
    options: ['The turn has already happened.', 'The driver is showing an intention, but wait for the vehicle’s actual movement.', 'The signal guarantees the path is safe for everyone.'],
    answer: 1,
    why: 'A turn signal communicates intent, but signals can be left on or plans can change. Watch the vehicle’s speed and position too.',
    hint: 'A signal is useful information, not a guarantee.',
    visual: 'vehicle-turn'
  },
  {
    id: 'ball-in-road',
    category: 'Vehicle & road hazards',
    title: 'Ball rolls into the street',
    prompt: 'A ball rolls from between parked cars into the roadway. What hidden hazard should you expect?',
    options: ['Nothing; balls roll by themselves.', 'A parking space is opening.', 'A child or pet may follow; slow or stop safely and scan both sides.'],
    answer: 2,
    why: 'A rolling toy can be an early clue that a child or pet is about to enter the road from a place that is hard to see.',
    hint: 'Look for what might come after the ball.',
    visual: 'scene-ball'
  },
  {
    id: 'heavy-fog',
    category: 'Vehicle & road hazards',
    title: 'Heavy fog',
    prompt: 'Fog makes the road and taillights hard to see. What is the safer plan?',
    options: ['Slow down, increase space, use appropriate low beams, and leave the road safely if visibility becomes too poor.', 'Use high beams and follow the nearest taillights closely.', 'Keep the same speed so other drivers are not surprised.'],
    answer: 0,
    why: 'Fog shortens how far you can see. A slower speed and more space improve reaction time; high beams can reflect glare back in fog.',
    hint: 'Match your speed and following space to how far you can actually see.',
    visual: 'scene-fog'
  },
  {
    id: 'soft-shoulder',
    category: 'Roadside caution',
    title: 'Soft shoulder',
    prompt: 'A yellow roadside sign says SOFT SHOULDER. What condition should a road user expect?',
    options: ['The unpaved edge may not support a vehicle safely, so stay on the roadway and slow if needed.', 'The shoulder is a special passing lane.', 'The road becomes soft enough for walking barefoot.'],
    answer: 0,
    why: 'A soft shoulder can be loose, uneven, or lower than the travel lane. Entering it suddenly can reduce control or make returning to pavement difficult.',
    hint: 'Compare the firm travel lane with the loose edge beside it.',
    visual: 'roadside-soft-shoulder'
  },
  {
    id: 'shoulder-dropoff',
    category: 'Roadside caution',
    title: 'Shoulder drop-off',
    prompt: 'An orange sign warns SHOULDER DROP-OFF beside fresh road work. What is the safe response?',
    options: ['Swerve onto the shoulder to test its height.', 'Stay in the lane, reduce speed as posted, and avoid sudden moves near the pavement edge.', 'Drive with one wheel on each surface.'],
    answer: 1,
    why: 'A drop-off means the shoulder is lower than the travel lane. Smooth steering and a safer speed help prevent a tire from catching the pavement edge.',
    hint: 'The two road surfaces are temporarily at different heights.',
    visual: 'roadside-dropoff'
  },
  {
    id: 'disabled-vehicle-roadside',
    category: 'Roadside caution',
    title: 'Disabled vehicle ahead',
    prompt: 'A car is stopped on the shoulder with hazard lights flashing. What should approaching road users do?',
    options: ['Slow down, give the stopped vehicle extra space, and move over when safe and required.', 'Stop beside it in the travel lane to ask questions.', 'Pass closely because hazard lights make a shield.'],
    answer: 0,
    why: 'A disabled vehicle may have people, tools, or debris nearby. More space and a lower speed protect both the stopped travelers and moving traffic.',
    hint: 'Flashing hazards mean the roadside area needs extra room.',
    visual: 'roadside-disabled'
  },
  {
    id: 'roadside-maintenance-worker',
    category: 'Roadside caution',
    title: 'Roadside worker and cones',
    prompt: 'A maintenance worker in a bright vest is beside the road with cones. What is the safest first plan?',
    options: ['Keep full speed because the worker is outside the lane.', 'Slow down, follow temporary controls, and leave generous space.', 'Drive between the cones to get a closer look.'],
    answer: 1,
    why: 'Workers can be close to moving traffic and equipment may enter the lane. Slowing early and following the cone path makes your movement predictable.',
    hint: 'Cones create a temporary safety space around a person at work.',
    visual: 'roadside-worker'
  },
  {
    id: 'farm-equipment-entry',
    category: 'Roadside caution',
    title: 'Tractor entering the road',
    prompt: 'A tractor is approaching from a farm driveway beside the road. What should a road user expect?',
    options: ['The tractor may enter slowly and need extra room, so reduce speed and be patient.', 'The tractor must disappear before reaching the pavement.', 'Pass immediately even if the view ahead is blocked.'],
    answer: 0,
    why: 'Farm equipment is often wide and slow and may need a large turning path. Patience and clear following space are safer than a rushed pass.',
    hint: 'Think about the tractor’s speed, width, and turning room.',
    visual: 'roadside-tractor'
  },
  {
    id: 'deer-near-roadside',
    category: 'Roadside caution',
    title: 'Deer near the roadway',
    prompt: 'One deer is standing near the roadside at dusk. What hidden risk should you remember?',
    options: ['Deer always stay still when they see lights.', 'More animals may follow; slow down, scan both sides, and be ready to stop safely.', 'Swerve into the opposite lane before the deer moves.'],
    answer: 1,
    why: 'Wild animals can move suddenly and often travel in groups. A controlled slowdown preserves space without creating the extra danger of an abrupt swerve.',
    hint: 'The animal you see may not be the only one nearby.',
    visual: 'roadside-deer'
  },
  {
    id: 'flashing-yellow-arrow',
    category: 'Signal lights',
    title: 'Flashing yellow arrow',
    prompt: 'A yellow left-turn arrow is flashing while oncoming traffic has a green light. What does it mean?',
    options: ['The turn is protected and oncoming traffic must stop.', 'You may turn in the arrow direction after yielding and checking that the movement is permitted and safe.', 'The signal is broken, so every vehicle should move at once.'],
    answer: 1,
    why: 'A flashing yellow arrow allows the indicated turn only after yielding to conflicting traffic and people in the crosswalk. It is not a protected turn.',
    hint: 'Flashing yellow permits caution; it does not give you the right-of-way.',
    visual: 'arrow-flashing-yellow'
  },
  {
    id: 'dark-traffic-signal',
    category: 'Signal lights',
    title: 'Dark traffic signal',
    prompt: 'Every lens on the traffic signal is dark during a power outage. What is the safest response?',
    options: ['Continue at normal speed because no color is showing.', 'Follow any officer or temporary control, slow down, and handle the intersection as local law requires.', 'Wait beneath the signal until the lights return.'],
    answer: 1,
    why: 'A dark signal is not permission to rush through. An officer or temporary sign controls first; otherwise drivers must use the cautious procedure required where they live.',
    hint: 'No working light means you need more caution and another valid control.',
    visual: 'signal-dark'
  },
  {
    id: 'curve-ahead',
    category: 'Caution signs',
    title: 'Sharp curve ahead',
    prompt: 'A yellow diamond shows a road bending sharply to the right. What should a road user do before the curve?',
    options: ['Reduce speed smoothly and stay in the lane through the bend.', 'Move across the center line for a straighter path.', 'Stop in the travel lane to study the sign.'],
    answer: 0,
    why: 'A curve warning gives time to choose a safe speed before steering through the bend. Staying in the lane protects road users coming the other way.',
    hint: 'Prepare before the bend instead of braking or swerving inside it.',
    visual: 'sign-curve'
  },
  {
    id: 'narrow-bridge',
    category: 'Caution signs',
    title: 'Narrow bridge',
    prompt: 'A yellow warning sign shows the roadway squeezing inward at a bridge. What is the important clue?',
    options: ['The bridge has less width than the approach, so slow down and avoid crowding others.', 'The bridge is a passing lane.', 'Every vehicle must turn around before the bridge.'],
    answer: 0,
    why: 'A narrow bridge provides less side-to-side space, especially around wide or oncoming vehicles. A controlled speed and careful lane position help.',
    hint: 'The road continues, but the usable width becomes smaller.',
    visual: 'sign-narrow-bridge'
  },
  {
    id: 'deer-crossing-sign',
    category: 'Caution signs',
    title: 'Deer crossing sign',
    prompt: 'A yellow diamond shows a deer leaping. What does the sign warn about?',
    options: ['A petting zoo entrance is required.', 'Wild animals may enter the roadway, so scan both sides and use a safer speed.', 'Drivers should honk continuously until the sign is gone.'],
    answer: 1,
    why: 'Animal-crossing signs mark places where wildlife may enter suddenly. Slowing attention is especially useful when visibility is limited or animals are active.',
    hint: 'The animal symbol warns about movement near the road, not a destination.',
    visual: 'sign-deer'
  },
  {
    id: 'low-clearance-sign',
    category: 'Caution signs',
    title: 'Low clearance',
    prompt: 'A bridge warning sign includes a height measurement. Why must a tall-vehicle driver notice it?',
    options: ['It gives the bridge length.', 'It shows how high pedestrians may jump.', 'The vehicle may not fit beneath the structure and may need another route.'],
    answer: 2,
    why: 'A low-clearance sign shows the available height beneath a structure. A vehicle that is too tall must not try to squeeze through or guess.',
    hint: 'Compare the posted height with the full height of the vehicle and load.',
    visual: 'sign-low-clearance'
  },
  {
    id: 'officer-directing-traffic',
    category: 'Emergency awareness',
    title: 'Officer directing traffic',
    prompt: 'A uniformed officer is directing traffic while the nearby signal shows a different movement. Which direction should be followed?',
    options: ['Follow the officer’s clear directions and move only when the path is safe.', 'Follow whichever direction lets you go first.', 'Ignore both controls and copy the nearest vehicle.'],
    answer: 0,
    why: 'An authorized person directing traffic can temporarily replace the normal signal pattern. Slow down, watch carefully, and follow the person’s clear directions.',
    hint: 'A real person may be managing a temporary problem at the intersection.',
    visual: 'emergency-officer'
  },
  {
    id: 'fire-truck-leaving-station',
    category: 'Emergency awareness',
    title: 'Fire truck leaving station',
    prompt: 'Warning lights flash outside a fire station as a fire truck begins to exit. What should nearby road users do?',
    options: ['Speed past before the truck reaches the road.', 'Stop or yield as the controls require and keep the station exit clear.', 'Park across the driveway to watch.'],
    answer: 1,
    why: 'Station warning lights alert road users that emergency equipment may enter quickly. Keeping the driveway clear gives the crew a predictable path.',
    hint: 'The large emergency vehicle needs the entire driveway and room to turn.',
    visual: 'emergency-fire-truck'
  },
  {
    id: 'blocked-emergency-scene',
    category: 'Emergency awareness',
    title: 'Blocked emergency scene',
    prompt: 'Cones and emergency vehicles block a lane around a crash scene. What is the safest way past?',
    options: ['Follow the temporary lane, slow down, and give responders plenty of room.', 'Drive between the cones for a closer look.', 'Stop beside the scene to take pictures.'],
    answer: 0,
    why: 'Emergency scenes can contain injured people, equipment, debris, and workers close to traffic. Temporary controls create a safer route around them.',
    hint: 'The cones show the path; the scene itself needs protected space.',
    visual: 'emergency-scene'
  },
  {
    id: 'fire-hose-across-road',
    category: 'Emergency awareness',
    title: 'Fire hose across the road',
    prompt: 'Firefighters have stretched a large hose across the street and the road is blocked. What should a driver do?',
    options: ['Drive over the hose slowly.', 'Move the hose if no firefighter is nearby.', 'Stop and use the route directed by emergency personnel.'],
    answer: 2,
    why: 'Driving over a fire hose can damage equipment and interrupt water reaching firefighters. Never cross it unless emergency personnel clearly direct you.',
    hint: 'The hose is working emergency equipment, not an ordinary road bump.',
    visual: 'emergency-hose'
  },
  {
    id: 'emergency-road-closure',
    category: 'Emergency awareness',
    title: 'Emergency road closure',
    prompt: 'A ROAD CLOSED barricade and flashing lights appear after a severe storm. What should road users do?',
    options: ['Go around the barricade if another car did.', 'Respect the closure and follow the official detour or instructions.', 'Wait beside the barricade in the travel lane.'],
    answer: 1,
    why: 'An emergency closure may protect people from flooding, fallen wires, unstable trees, or damaged pavement that cannot be seen from the barrier.',
    hint: 'A barricade protects you from hazards that may be hidden farther ahead.',
    visual: 'emergency-road-closed'
  },
  {
    id: 'emergency-vehicle-crossing-green',
    category: 'Emergency awareness',
    title: 'Siren crosses your green light',
    prompt: 'Your signal is green, but an emergency vehicle with lights and siren is entering the intersection. What should happen?',
    options: ['Enter first because green always wins.', 'Stay clear, yield as local law directs, and move only after the emergency vehicle and scene are safe.', 'Follow closely behind the emergency vehicle.'],
    answer: 1,
    why: 'A green light never makes it safe to block an emergency vehicle. Staying predictable and clear helps responders cross without creating another crash.',
    hint: 'The intersection must be clear even when your normal signal permits movement.',
    visual: 'emergency-intersection'
  },
  {
    id: 'truck-blind-spot',
    category: 'Vehicle & road hazards',
    title: 'Large-truck blind spot',
    prompt: 'A bicycle or small car is traveling beside the rear half of a large truck. What hazard should they remember?',
    options: ['The truck driver may not see them, so avoid lingering beside the truck and leave room.', 'The truck can stop and turn faster than a small vehicle.', 'The space beside every truck is a protected lane.'],
    answer: 0,
    why: 'Large vehicles have substantial blind areas and need extra room to turn. Staying visible and avoiding a long ride beside the truck reduces risk.',
    hint: 'If you cannot see the truck driver or mirrors, visibility may be limited.',
    visual: 'scene-truck-blind-spot'
  },
  {
    id: 'debris-in-road',
    category: 'Vehicle & road hazards',
    title: 'Debris in the roadway',
    prompt: 'A box has fallen into the lane ahead. What is the safest general response?',
    options: ['Swerve suddenly without checking nearby traffic.', 'Slow in a controlled way, check around you, and avoid the object only when the path is safe.', 'Hit the box so another vehicle does not have to.' ],
    answer: 1,
    why: 'Road debris can hide sharp or heavy material. A controlled slowdown and awareness of nearby road users are safer than a sudden unplanned swerve.',
    hint: 'Create time and check the space around you before changing your path.',
    visual: 'scene-debris'
  },
  {
    id: 'icy-bridge',
    category: 'Vehicle & road hazards',
    title: 'Icy bridge surface',
    prompt: 'A bridge deck looks shiny on a freezing morning. Why does it need extra caution?',
    options: ['Bridges can freeze before nearby roads, so reduce speed and use smooth steering and braking.', 'Shiny pavement always has more grip.', 'The safest plan is to accelerate across it.'],
    answer: 0,
    why: 'Cold air reaches above and below a bridge deck, so ice can form there before it appears on ordinary pavement. Smooth actions help preserve traction.',
    hint: 'The bridge surface is exposed to cold air on more than one side.',
    visual: 'scene-ice'
  },
  {
    id: 'opening-car-door',
    category: 'Vehicle & road hazards',
    title: 'Parked car door opens',
    prompt: 'A parked car’s door begins opening beside a bike lane. What should a rider or driver nearby do?',
    options: ['Keep full speed because parked cars cannot be hazards.', 'Slow down, create safe space, and watch for the person without swerving blindly.', 'Honk and pass between the door and curb.'],
    answer: 1,
    why: 'An opening door can suddenly block a rider’s path. Slower speed, visible positioning, and a checked escape space help prevent a collision.',
    hint: 'A person inside a parked vehicle may not see everyone approaching from behind.',
    visual: 'scene-open-door'
  },
  {
    id: 'wet-following-distance',
    category: 'Vehicle & road hazards',
    title: 'Following in heavy rain',
    prompt: 'Heavy rain reduces visibility and makes the road slick. What should happen to following space?',
    options: ['Increase it so there is more time to see, slow, and stop.', 'Make it smaller so the vehicle ahead is easier to see.', 'Keep exactly the same gap in every condition.'],
    answer: 0,
    why: 'Rain can increase stopping distance and hide hazards. Extra space gives road users more time to react with smooth steering and braking.',
    hint: 'When grip and visibility decrease, the time cushion should grow.',
    visual: 'scene-following'
  },
  {
    id: 'low-sun-glare',
    category: 'Vehicle & road hazards',
    title: 'Low sun glare',
    prompt: 'Low sunlight makes the signal and people ahead difficult to see. What is the safer plan?',
    options: ['Speed up to leave the bright area quickly.', 'Close your eyes for short moments.', 'Slow down, increase space, use safe glare controls, and stop somewhere safe if you cannot see.'],
    answer: 2,
    why: 'Glare can hide signals, vehicles, and people. Reducing speed and increasing space match movement to the shorter distance that is actually visible.',
    hint: 'Never travel faster than your available view lets you respond safely.',
    visual: 'scene-sun-glare'
  },
  {
    id: 'cow-near-roadside',
    category: 'Roadside caution',
    title: 'Cow near the road',
    prompt: 'A cow stands beside a rural road near an open gate. What should a road user expect?',
    options: ['The animal may enter unpredictably, so slow down and be ready to stop without a sudden swerve.', 'The cow will always wait for a hand signal.', 'Passing quickly will keep every animal still.'],
    answer: 0,
    why: 'Livestock can move into the roadway without warning and more animals may be nearby. A controlled slowdown creates time without adding a sharp swerve.',
    hint: 'An open gate means the roadside animal may not stay behind a fence.',
    visual: 'roadside-cow'
  },
  {
    id: 'fallen-rocks-roadside',
    category: 'Roadside caution',
    title: 'Rocks below a steep slope',
    prompt: 'Fresh rocks lie on the shoulder below a steep roadside cut. What clue do they provide?',
    options: ['More debris could reach the road, so scan ahead and avoid stopping under the slope.', 'The shoulder is a rock-collection area.', 'The travel lane is guaranteed clear around every bend.'],
    answer: 0,
    why: 'Fresh fallen material can signal an unstable slope, and rocks may already be hidden around the curve. Attention and a safe speed give more response time.',
    hint: 'The pieces on the ground may show where they came from and what could happen next.',
    visual: 'roadside-rocks'
  },
  {
    id: 'cyclist-on-shoulder',
    category: 'Roadside caution',
    title: 'Cyclist on the shoulder',
    prompt: 'A cyclist is traveling near the edge line as the shoulder becomes narrow. What should a driver plan for?',
    options: ['The cyclist may need more lane space; slow down and pass only with safe, legal clearance.', 'The cyclist must disappear when the shoulder ends.', 'Pass immediately even when oncoming traffic blocks the view.'],
    answer: 0,
    why: 'A narrow or blocked shoulder can move a cyclist closer to the travel lane. Waiting for enough visible, legal space is safer than squeezing past.',
    hint: 'The road edge may change, but the person still needs a safe path.',
    visual: 'roadside-cyclist'
  },
  {
    id: 'hidden-driveway',
    category: 'Roadside caution',
    title: 'Hidden driveway',
    prompt: 'Bushes and a hill hide part of a driveway entrance beside the road. What should road users remember?',
    options: ['A vehicle, person, or bicycle may appear with little warning, so scan and use a safer speed.', 'Nothing can enter because the driveway is hard to see.', 'The driveway is a passing lane.' ],
    answer: 0,
    why: 'Limited sight distance makes it harder for everyone to see one another. Slower, attentive travel provides more time if someone enters from the hidden driveway.',
    hint: 'If you cannot see into the driveway, someone there may not see you either.',
    visual: 'roadside-driveway'
  },
  {
    id: 'guardrail-curve',
    category: 'Roadside caution',
    title: 'Guardrail on a sharp curve',
    prompt: 'Chevron signs and a guardrail trace a sharp roadside curve. What do these clues show?',
    options: ['The road bends sharply, so slow before the curve and follow the marked direction.', 'The guardrail is a parking barrier.', 'Crossing the center line makes the curve safer.'],
    answer: 0,
    why: 'Chevron signs visually continue the direction of a sharp bend, while the guardrail marks the road edge. Both help road users read the curve early.',
    hint: 'Follow the repeated arrows and the road edge instead of cutting across the bend.',
    visual: 'roadside-guardrail'
  },
  {
    id: 'tow-truck-roadside',
    category: 'Roadside caution',
    title: 'Tow truck working roadside',
    prompt: 'A tow truck has flashing lights while a worker connects a disabled car on the shoulder. What should approaching traffic do?',
    options: ['Pass closely so traffic behind does not slow.', 'Move over when safe and required, or slow down and leave extra space.', 'Stop beside the worker to ask what happened.'],
    answer: 1,
    why: 'Tow operators work close to moving traffic and may step around vehicles or equipment. More space and a lower speed protect the worker and stranded travelers.',
    hint: 'Flashing roadside lights mean people and equipment may be near the lane.',
    visual: 'roadside-tow'
  }
]);

export const streetSafetyCategories = Object.freeze([
  'Signal lights',
  'Caution signs',
  'Emergency awareness',
  'Vehicle & road hazards',
  'Roadside caution'
]);
