'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const W=1000,H=600,PHI=1.618,LAM=.618,R=28,WALL=18,COLS=16,ROWS=10,HEX=Math.sqrt(3)*R;
const SHOT_SPEED=9,MIN_UPWARD_RATIO=.38,MAX_BOUNCES=6,MAX_TRAVEL=H*3,DROP_AFTER=5,DROP_MS=360;
const left=WALL,right=W-WALL,top=WALL,bottom=H-10,x0=left+R+2,y0=top+R+2;
const GAME_ID='bubble-resonance-phi369';
const FREQS=[
  ['396 Hz','Liberating Guilt','#e26c6c','#5a1818',396],['417 Hz','Undoing Situations','#e8934a','#5a2808',417],
  ['528 Hz','DNA Repair','#d4c44a','#4a3c00',528],['639 Hz','Connecting','#5dcaa5','#0a3a28',639],
  ['741 Hz','Awakening Intuition','#5a9ee8','#0a1e4a',741],['852 Hz','Returning to Order','#a07de0','#200a4a',852]
].map(([name,label,color,dark,hz])=>({name,label,color,dark,hz}));
let grid=[],score=0,combo=1,level=1,coherence=50,pattern=0,integration=50,cleared=0,misses=0;
let current,next,shot=null,particles=[],gameOver=false,audioOn=false,audioCtx,awarded=false,mouse={x:W/2,y:100},messageTimer,dropAnimation=null;
const $=s=>document.querySelector(s),pos=(c,r)=>({x:x0+c*R*2+(r%2?R:0),y:y0+r*HEX});
const rand=()=>Math.floor(Math.random()*FREQS.length),distance=(a,b,c,d)=>Math.hypot(a-c,b-d);
function profile(){return window.LarriVerseArcade?.summary?.()||{name:'Player One',avatar:'🌟',level:1,kc:0,games:{}}}
function refreshProfile(){const p=profile(),g=p.games?.[GAME_ID]||{};$('#playerName').textContent=`${p.avatar||'🌟'} ${p.name||'Player One'}`;$('#playerLevel').textContent=p.level||1;$('#playerKc').textContent=p.kc||0;$('#bestScore').textContent=(g.highScore||0).toLocaleString()}
function toast(text){const n=$('#toast');n.textContent=text;n.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.remove('show'),2600)}
function award(){if(awarded||!window.LarriVerseArcade?.award)return;awarded=true;const completed=score>=369||cleared>=9,kc=score>=3600?9:score>=1200?6:3,xp=Math.max(9,Math.min(99,9+level*3+Math.floor(cleared/3)));const r=window.LarriVerseArcade.award(GAME_ID,{xp,kc,score,catches:cleared,completed});refreshProfile();toast(`FIELD RECORDED · +${xp} XP · +${kc} KC${r.milestoneBonus?` +${r.milestoneBonus} BONUS`:''}${r.unlocked?.length?` · ${r.unlocked.length} ACHIEVEMENT`:''}`)}
function ac(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
function tone(hz,type='sine',duration=.2,volume=.07){if(!audioOn)return;try{const a=ac(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.type=type;o.frequency.value=hz;g.gain.setValueAtTime(volume,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+duration);o.start();o.stop(a.currentTime+duration+.02)}catch{}}
function cellY(r){return y0+r*HEX}
function neighbours(r,c,occupiedOnly=true){const offsets=r%2?[[-1,0],[-1,1],[0,-1],[0,1],[1,0],[1,1]]:[[-1,-1],[-1,0],[0,-1],[0,1],[1,-1],[1,0]];return offsets.map(([dr,dc])=>({r:r+dr,c:c+dc})).filter(n=>n.r>=0&&n.r<ROWS&&n.c>=0&&n.c<COLS&&(!occupiedOnly||grid[n.r]?.[n.c]))}
function initGrid(){grid=Array.from({length:ROWS},(_,r)=>Array.from({length:COLS},(_,c)=>r<5?{freq:rand(),gem:c%2===0&&r%3===0&&Math.random()<.12,...pos(c,r)}:null))}
function nextBubble(){current=next||{freq:rand(),gem:false};next={freq:rand(),gem:Math.random()<.05};$('#bubbleStatus').textContent=`Your bubble: ${current.freq+1} · ${FREQS[current.freq].name}. Next: ${next.freq+1} · ${FREQS[next.freq].name}. Match the numbers; color is an extra clue.`}
function cluster(r,c,freq,seen=new Set()){const key=`${r},${c}`;if(seen.has(key)||!grid[r]?.[c]||grid[r][c].freq!==freq)return[];seen.add(key);return[{r,c},...neighbours(r,c).flatMap(n=>cluster(n.r,n.c,freq,seen))]}
function floating(){const connected=new Set(),queue=[];for(let c=0;c<COLS;c++)if(grid[0][c]){queue.push({r:0,c});connected.add(`0,${c}`)}while(queue.length){const n=queue.shift();for(const x of neighbours(n.r,n.c)){const k=`${x.r},${x.c}`;if(!connected.has(k)){connected.add(k);queue.push(x)}}}const result=[];for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++)if(grid[r][c]&&!connected.has(`${r},${c}`))result.push({r,c});return result}
function particlesAt(x,y,color,count=10){if(window.LarriVerseArcade.settings().reducedMotion)return;for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=1.3+Math.random()*3.4;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,color,life:1,size:2+Math.random()*3})}}
function announce(title,sub,color='#5dcaa5',sticky=false){const m=$('#message');m.querySelector('b').textContent=title;m.querySelector('b').style.color=color;m.querySelector('span').textContent=sub;m.classList.add('show');clearTimeout(messageTimer);if(!sticky)messageTimer=setTimeout(()=>m.classList.remove('show'),1200)}
function updateCoherence(){coherence=Math.round(Math.min(100,Math.max(0,PHI*(pattern/10+integration/10)+(combo-1)*2-LAM*(10-combo)*2)));$('#coherenceFill').style.width=`${coherence}%`;$('#coherenceValue').textContent=coherence}
function hud(){$('#score').textContent=score.toLocaleString();$('#combo').textContent=`×${combo}`;$('#combo').style.color=combo>=5?'#d4c44a':combo>=3?'#e8934a':'#5dcaa5';$('#level').textContent=level;$('#dropIn').textContent=Math.max(0,DROP_AFTER-misses);$('#limit').textContent=gameOver?'FULL':'CLEAR';$('#limit').style.color=gameOver?'#e26c6c':'#5dcaa5'}
function phiMultiplier(size){return size>=13?4:size>=8?3:size>=5?PHI:1}
function place(x,y){let best,bestD=Infinity,fallback,fallbackD=Infinity;for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){if(grid[r][c])continue;const p=pos(c,r),d=distance(x,y,p.x,p.y),adjacent=r<=1||neighbours(r,c).length;if(!adjacent)continue;if(d<fallbackD){fallback={r,c,...p};fallbackD=d}if(d<R*2.8&&d<bestD){best={r,c,...p};bestD=d}}best||=fallback;if(!best)return false;grid[best.r][best.c]={freq:current.freq,gem:current.gem,x:best.x,y:best.y};const group=cluster(best.r,best.c,current.freq);if(group.length>=3){misses=0;const f=FREQS[current.freq],mult=phiMultiplier(group.length),gem=group.some(n=>grid[n.r][n.c].gem);score+=Math.round(group.length*10*mult*(gem?2:1)*combo);combo=Math.min(9,combo+1);cleared+=group.length;pattern=Math.min(100,pattern+group.length*3);integration=Math.min(100,integration+group.length);tone(f.hz,'sine',.55,.12);group.forEach(n=>{particlesAt(grid[n.r][n.c].x,grid[n.r][n.c].y,f.color,12);grid[n.r][n.c]=null});const drop=floating();score+=drop.length*8;drop.forEach(n=>{particlesAt(grid[n.r][n.c].x,grid[n.r][n.c].y,f.color,6);grid[n.r][n.c]=null});announce(group.length>=8?'PHI CHAIN':'RESONANCE',`${f.name} ×${mult.toFixed(1)}`,f.color);if(score>=level*1200){level++;announce(`LEVEL ${level}`,'coherence deepens','#d4c44a')}}else{misses++;combo=Math.max(1,combo-1);tone(200)}updateCoherence();if(danger()){hud();return true}if(misses>=DROP_AFTER)ceilingDrop();hud();return true}
function danger(){if(grid[ROWS-1].some(Boolean)){end('BOTTOM REACHED','The stack reached the launch zone. Your bubbles stay visible so you can see what happened.');return true}return false}
function ceilingDrop(){if(gameOver||dropAnimation)return;const shifted=Array.from({length:ROWS},()=>Array(COLS).fill(null));for(let r=ROWS-1;r>=1;r--)for(let c=0;c<COLS;c++){const bubble=grid[r-1][c];if(bubble)shifted[r][c]={...bubble,...pos(c,r)}}for(let c=0;c<COLS;c++)shifted[0][c]={freq:rand(),gem:c%4===0&&Math.random()<.12,...pos(c,0)};grid=shifted;misses=0;dropAnimation={start:performance.now(),duration:DROP_MS};canvas.setAttribute('aria-busy','true');announce('CEILING DROP','Fresh bubbles are moving the field down one row','#d4c44a');hud()}
function end(title='FIELD EXPLORED',sub=`score: ${score} · cleared: ${cleared} · try another round when ready`){gameOver=true;shot=null;canvas.setAttribute('aria-busy','false');award();$('#reset').textContent='Try another round';announce(title,sub,'#e26c6c',true);tone(60,'sawtooth',1,.15);hud()}
function shotDirection(tx,ty){const sx=W/2,sy=bottom-R-6,dx=tx-sx,dy=ty-sy;if(dy>=0)return null;const len=Math.hypot(dx,dy)||1;let ux=dx/len,uy=dy/len;if(-uy<MIN_UPWARD_RATIO){uy=-MIN_UPWARD_RATIO;ux=Math.sign(ux||1)*Math.sqrt(1-uy*uy)}return{x:ux,y:uy}}
function fire(tx,ty){if(shot||gameOver||dropAnimation)return;const sx=W/2,sy=bottom-R-6,dir=shotDirection(tx,ty);if(!dir)return;shot={x:sx,y:sy,vx:dir.x*SHOT_SPEED,vy:dir.y*SHOT_SPEED,bounces:0,travel:0};canvas.setAttribute('aria-busy','true');tone(440,'sine',.1,.07)}
function autoFire(){const a=-Math.PI/2+(Math.random()-.5)*Math.PI*.7;fire(W/2+Math.cos(a)*200,bottom-R-6+Math.sin(a)*200)}
function settleShot(x,y){if(place(x,y)){shot=null;if(!dropAnimation)canvas.setAttribute('aria-busy','false');nextBubble();return true}shot=null;canvas.setAttribute('aria-busy','false');end();return true}
function stepShot(){if(!shot)return;for(let i=0;i<6;i++){const dxStep=shot.vx/6,dyStep=shot.vy/6;shot.x+=dxStep;shot.y+=dyStep;shot.travel+=Math.hypot(dxStep,dyStep);if(shot.x<=left+R){shot.x=left+R;shot.vx=Math.abs(shot.vx);shot.bounces++;tone(200,'square',.04,.03)}if(shot.x>=right-R){shot.x=right-R;shot.vx=-Math.abs(shot.vx);shot.bounces++;tone(200,'square',.04,.03)}if(shot.bounces>MAX_BOUNCES||shot.travel>MAX_TRAVEL){settleShot(shot.x,shot.y);announce('SHOT SETTLED','Try a steeper angle for a cleaner bank shot','#5dcaa5');return}if(shot.y<=top+R){shot.y=top+R;settleShot(shot.x,shot.y);return}for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){const b=grid[r][c];if(b&&distance(shot.x,shot.y,b.x,b.y)<R*1.82){const dx=shot.x-b.x,dy=shot.y-b.y,d=Math.hypot(dx,dy)||1;settleShot(b.x+dx/d*R*1.82,b.y+dy/d*R*1.82);return}}}}
function hex(x,y,r,freq,gem=false,alpha=1){const f=FREQS[freq];ctx.save();ctx.globalAlpha=alpha;ctx.beginPath();for(let i=0;i<6;i++){const a=Math.PI/6+i*Math.PI/3,p=[x+r*Math.cos(a),y+r*Math.sin(a)];i?ctx.lineTo(...p):ctx.moveTo(...p)}ctx.closePath();ctx.fillStyle=f.dark;ctx.fill();ctx.strokeStyle=f.color;ctx.lineWidth=1.5;ctx.stroke();ctx.beginPath();ctx.arc(x,y,r*.18,0,Math.PI*2);ctx.fillStyle=f.color;ctx.fill();ctx.fillStyle='#fff';ctx.font=`bold ${r*.85}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(freq+1),x,y);if(gem){ctx.font=`bold ${r}px Rajdhani`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`bold ${r*.6}px system-ui`;ctx.fillText('✦',x+r*.55,y-r*.55)}ctx.restore()}
function aim(){if(shot||gameOver||dropAnimation)return;const sx=W/2,sy=bottom-R-6,dir=shotDirection(mouse.x,mouse.y);if(!dir)return;let x=sx,y=sy,vx=dir.x*3,vy=dir.y*3;ctx.save();ctx.setLineDash([4,8]);ctx.strokeStyle='#5dcaa577';ctx.beginPath();ctx.moveTo(x,y);for(let i=0;i<260;i++){x+=vx;y+=vy;if(x<=left+R){x=left+R;vx=Math.abs(vx)}if(x>=right-R){x=right-R;vx=-Math.abs(vx)}ctx.lineTo(x,y);if(y<=top+R||grid.some(row=>row.some(b=>b&&distance(x,y,b.x,b.y)<R*1.82)))break}ctx.stroke();ctx.restore()}
function draw(now=performance.now()){ctx.clearRect(0,0,W,H);ctx.fillStyle='#5dcaa526';ctx.fillRect(0,0,WALL,H);ctx.fillRect(W-WALL,0,WALL,H);ctx.fillRect(0,0,W,WALL);let dropOffset=0;if(dropAnimation){const t=Math.min(1,(now-dropAnimation.start)/dropAnimation.duration);const eased=1-Math.pow(1-t,3);dropOffset=-HEX*(1-eased);if(t>=1){dropAnimation=null;canvas.setAttribute('aria-busy','false');if(danger())hud()}}for(const row of grid)for(const b of row)if(b)hex(b.x,b.y+dropOffset,R,b.freq,b.gem);ctx.save();ctx.setLineDash([3,7]);ctx.strokeStyle='#e26c6c2e';ctx.beginPath();const dangerY=Math.min(bottom-R*2.2,cellY(ROWS-1)+R+8);ctx.moveTo(left,dangerY);ctx.lineTo(right,dangerY);ctx.stroke();ctx.restore();aim();const sx=W/2,sy=bottom-R-6;if(!gameOver)hex(sx,sy,R,current.freq,current.gem);stepShot();if(shot)hex(shot.x,shot.y,R,current.freq,current.gem);if(next&&!gameOver)hex(right-30,bottom-30,R*.7,next.freq,next.gem,.75);for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx;p.y+=p.vy;p.vy+=.08;p.life-=.022;if(p.life<=0){particles.splice(i,1);continue}ctx.globalAlpha=p.life;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}requestAnimationFrame(draw)}
function point(e){const rect=canvas.getBoundingClientRect(),t=e.touches?.[0]||e.changedTouches?.[0]||e;return{x:(t.clientX-rect.left)*W/rect.width,y:(t.clientY-rect.top)*H/rect.height}}
function reset(){$('#reset').textContent='↺ Start over';canvas.setAttribute('aria-busy','false');gameOver=false;awarded=false;score=0;combo=1;level=1;coherence=50;pattern=0;integration=50;cleared=0;misses=0;shot=null;dropAnimation=null;particles=[];$('#message').classList.remove('show');initGrid();nextBubble();hud();updateCoherence();refreshProfile()}
canvas.addEventListener('mousemove',e=>mouse=point(e));canvas.addEventListener('touchmove',e=>{e.preventDefault();mouse=point(e)},{passive:false});canvas.addEventListener('click',e=>{const p=point(e);gameOver?reset():fire(p.x,p.y)});canvas.addEventListener('touchend',e=>{e.preventDefault();const p=point(e);gameOver?reset():fire(p.x,p.y)},{passive:false});
$('#reset').onclick=reset;$('#auto').onclick=autoFire;$('#sound').onclick=()=>{audioOn=!audioOn;$('#sound').textContent=audioOn?'♪ Sound ON':'♪ Sound OFF';$('#sound').classList.toggle('active',audioOn);$('#sound').setAttribute('aria-pressed',String(audioOn));if(audioOn)ac()};function aimBy(amount){mouse.x=Math.max(left+R,Math.min(right-R,mouse.x+amount));mouse.y=100;}
function fireAimed(){if(!document.querySelector('dialog[open]'))gameOver?reset():fire(mouse.x,mouse.y);}
$('#aimLeft').onclick=()=>aimBy(-32);$('#aimRight').onclick=()=>aimBy(32);$('#fireAimed').onclick=fireAimed;
canvas.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();aimBy(e.key==='ArrowLeft'?-32:32)}if(e.code==='Space'||e.key==='Enter'){e.preventDefault();fireAimed()}if(e.key.toLowerCase()==='r')reset()});
window.addEventListener('larriverse:settings',()=>{if(window.LarriVerseArcade.settings().reducedMotion)particles=[]});
window.addEventListener('larriverse:profile',refreshProfile);
$('#legend').innerHTML=FREQS.map((f,index)=>`<span><i style="background:${f.color}"></i><b>${index+1}</b> · ${f.name} · ${f.label}</span>`).join('');reset();draw();
